### ISSUE TITLE
Move from html2jade, to html2pug, to correctly support attribute casing

### ISSUE THREAD

**Issue by lunelson** [dbalas/vscode-html2pug#1]
Hi there,

wondering if you would accept a PR that change the dependency of this package from [html2jade](https://github.com/donpark/html2jade) to [html2pug](https://github.com/izolate/html2pug). The reason is html2jade has a long-standing [problem concerning camelCase attributes](https://github.com/donpark/html2jade/issues/102), which makes it useless for XML-based markup e.g. SVG, and for js-framework code such as Angular.

**Comment by dbalas** [comment]
Hi

Of course I would accept! 

Thabks for your interest :)

**Comment by sublime392** [comment]
This doesn't seem to be working anymore. Attributes are all lower cased.

**Comment by lunelson** [comment]
I just did it on some SVG code and got the correct result -- note `viewBox`. Is this broken for you?

```pug
svg(xmlns='http://www.w3.org/2000/svg' xlink='http://www.w3.org/1999/xlink' viewBox='0 0 1052.4 744.1')
```

**Comment by sublime392** [comment]
That example does work for me. Here is e that does not:
`<div class="controls-top" *ngIf="slides.length > 1 && !checkNavigation() && isControls"></div>`

**Comment by lunelson** [comment]
It it looks like an issue with [html2pug](https://github.com/izolate/html2pug). You can try their conversion online [here](https://html2pug.com/)—this is what I got:
```pug
.controls-top(*ngif='slides.length > 1 && !checkNavigation() && isControls')
```
…so maybe I spoke too soon on the "correct attribute casing"; I guess it's set up to do it for specific attributes and doesn't recognize your angular directive
