### ISSUE TITLE
[FEATURE] Configure self-closing tags

### ISSUE THREAD

**Issue by the-nicolas** [dbalas/vscode-html2pug#107]
## Background

Right now it seems not to be possible to configure the tag names which get treated as self-closing. We are using pug for Vue templates and we have many HTML components with self-closing tags. When we convert them to pug they are all broken...

## Sample
```
<root>
  <menu>
    <menu-item>xxx</menu-item>
    <menu-item>xxx</menu-item>
    <menu-separator/>
    <menu-item>xxx</menu-item>
  </menu>
</root>
```

Gets converted to
```
root
  menu
    menu-item xxx
    menu-item xxx
    menu-separator
      menu-item xxx
```
Problem: Last menu-item after separator is now child of separator

## Solution

Have configuration to inject a list of custom self-closing tag names.

It looks like html2pug is not supporting that out of the box, but perhaps you have an idea...

**Comment by dbalas** [comment]
Hello, this is a simple wrapper around html2pug so maybe we can open an issue in html2pug about this.
