### ISSUE TITLE
Configuration file, ability to disable commas between attributes

### ISSUE THREAD

**Issue by PassTheMayo** [dbalas/vscode-html2pug#12]
Hey, great extension, I use it a lot. Is where a way to add a configuration file so that I can disable the use of commas between attributes? I would just find & replace `, `, but I always have commas in different locations in the file, and find/replacing each one is tedious. Thanks!

**Comment by dbalas** [comment]
Hi!
I had planned to do it this week :smile: 
Thank you!

**Comment by dbalas** [comment]
Hey @PassTheMayo I added options in settings in the 2.0.0 version!
Thanks for use it :)

**Comment by PassTheMayo** [comment]
Thank you!
