### ISSUE TITLE
Is there a way to use this ext inside another ext?

### ISSUE THREAD

**Issue by mehrunrasoli** [dbalas/vscode-html2pug#3]
There's a package (vuetify-vscode)[https://github.com/vuetifyjs/vuetify-vscode] which provides a set of snippet codes as HTML, but I'm looking for a way to somehow use html2pug, so the snippets output be in PUG not in HTML.

**Comment by dbalas** [comment]
Hello!
I think the best way is to add an option in vuetify-vscode to use PUG instead of HTML. It will be faster, but you can use html2pug to automate the transformation.
