### ISSUE TITLE
Please update to new html2pug version 

### ISSUE THREAD

**Issue by 7iomka** [dbalas/vscode-html2pug#4]
Hi
See please
https://github.com/izolate/html2pug/releases
I prefer to use two quotes in pug, so oldest html2pug transform html to pug with single quotes in attibutes without posibility to setup this!
Thanks!

**Comment by dbalas** [comment]
Hello 7iomka,  
I would be very grateful if you could do a pull request!

Thank you

**Comment by 7iomka** [comment]
> Hello 7iomka,
> I would be very grateful if you could do a pull request!
> 
> Thank you

I'm unfortunately not strong in git ... I just stated the fact that such an important and only thing you might need to set up - quotes format - cannot be configured in the current version of your plug-in wrapper, and the new version of the vendor allows you to highlight this setting (I suppose)

**Comment by dbalas** [comment]
Ok, I will consider it for the next version :)

**Comment by dbalas** [comment]
Hello,

I already updated this extension with html2pug 3.0.0, but the library doesn't support double quotes yet. I will remain this issue opened, maybe in the near future they will update html2pug with this option.

**Comment by dbalas** [comment]
coming soon!

**Comment by 7iomka** [comment]
> coming soon!

[Finally](https://github.com/izolate/html2pug/blob/master/CHANGELOG.md#310---2019-05-14)) I look forward to!)

**Comment by izolate** [comment]
Hi @7iomka and @dbalas, I've published `html2pug@4.0.0` with an option to enable double quotes in attributes. This release contains breaking changes, so please refer to the readme for the updated option keys.

**Comment by dbalas** [comment]
wow thank you @izolate! :taco:
I will publish a new version asap

**Comment by 7iomka** [comment]
> wow thank you @izolate! 🌮
> I will publish a new version asap

I see a new version - it has appeared. I updated but I do not understand where in the settings to find the desired option? Tell me please

**Comment by dbalas** [comment]
You have to add "html2pug" object in your user/workspace settings.json, check this doc https://code.visualstudio.com/docs/getstarted/settings

**Comment by 7iomka** [comment]
> html2pug

I'm try, but nothing happens
![image](https://user-images.githubusercontent.com/18473137/57769680-33e35380-7717-11e9-8943-de0ebf14403d.png)

**Comment by izolate** [comment]
@7iomka The option is now `"doubleQuotes"` instead of `"useDoubleQuotes"`. See the [readme](https://github.com/izolate/html2pug#options) for the available options.

**Comment by 7iomka** [comment]
> @7iomka The option is now `"doubleQuotes"` instead of `"useDoubleQuotes"`. See the [readme](https://github.com/izolate/html2pug#options) for the available options.

but why i see message unknown configuration setting seems html2pug namespace is not exist
but I will try
